databases:
  - name: antiracism-dc-db
    databaseName: antiracism_dc
    user: antiracism_dc_user
    plan: free

services:
  - type: web
    name: antiracism-dc
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py createsuperuser --noinput || true"
    startCommand: "gunicorn config.wsgi:application --timeout 120"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "True"
      - key: DJANGO_HSTS_SECONDS
        value: "300"
      - key: DATABASE_URL
        fromDatabase:
          name: antiracism-dc-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
