# Generated by Django 6.0.2 on 2026-02-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=20)),
                ('primary_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_role', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('anti_racism_focus', models.TextField()),
                ('primary_anti_racist_engagement_type', models.CharField(max_length=255)),
                ('core_organizational_activities', models.TextField()),
                ('description_of_anti_racist_activities', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['organization_name'],
            },
        ),
    ]
