# Generated by Django 6.0.2 on 2026-02-23 10:24

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('orgs', '0004_historicalorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
            ],
            options={
                'verbose_name': 'Activity log',
                'verbose_name_plural': 'Activity logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.RenameField(
            model_name='historicalorganization',
            old_name='external_id',
            new_name='organization_id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='external_id',
            new_name='organization_id',
        ),
    ]
