# Generated by Django 6.0.2 on 2026-05-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_alter_historicalorganization_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='strategic_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='strategic_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
